export default [
  "exactly matches",
  "does not exactly match",
  "contains",
  "contains (ignore case)",
  "does not contain",
  "does not contain (ignore case)",
  "starts with",
  "starts with (ignore case)",
  "ends with",
  "split by",
  "matches regex",
  "does not match regex",
  "is empty",
  "is not empty",
  ">",
  ">=",
  "<",
  "<=",
  "=",
];
